version: '3.8'
services:
  # nest-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-api
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres:postgres
  #   env_file: ./.env
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

  postgres:
    image: postgres:alpine
    restart: always
    env_file: ./.env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
