# version: '3.8'
# services:
# nest-api:
#   build:
#     context: .
#     dockerfile: Dockerfile
#   container_name: nest-api
#   restart: always
#   ports:
#     - 3000:3000
#   depends_on:
#     - postgres
#   links:
#     - postgres:postgres
#   env_file: ./.env
#   volumes:
#     - .:/app
#     - /app/node_modules

version: '3.1'

services:
  db:
    container_name: 'test-postgres'
    restart: unless-stopped
    image: 'postgres:13'
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
